# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: e3sm_simple.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x65\x33sm_simple.proto\x12\x12libe3.sm.simple.v1\"%\n\x15SimpleRanFunctionData\x12\x0c\n\x04name\x18\x01 \x01(\t\"G\n\x10SimpleIndication\x12\r\n\x05\x64\x61ta1\x18\x01 \x01(\r\x12\x16\n\ttimestamp\x18\x02 \x01(\rH\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"G\n\rSimpleControl\x12\x1f\n\x12sampling_threshold\x18\x01 \x01(\rH\x00\x88\x01\x01\x42\x15\n\x13_sampling_threshold\"%\n\x13SimpleConfigControl\x12\x0e\n\x06\x65nable\x18\x01 \x01(\x08\" \n\x10SimpleDAppReport\x12\x0c\n\x04\x62in1\x18\x01 \x01(\rb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'e3sm_simple_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SIMPLERANFUNCTIONDATA._serialized_start=41
  _SIMPLERANFUNCTIONDATA._serialized_end=78
  _SIMPLEINDICATION._serialized_start=80
  _SIMPLEINDICATION._serialized_end=151
  _SIMPLECONTROL._serialized_start=153
  _SIMPLECONTROL._serialized_end=224
  _SIMPLECONFIGCONTROL._serialized_start=226
  _SIMPLECONFIGCONTROL._serialized_end=263
  _SIMPLEDAPPREPORT._serialized_start=265
  _SIMPLEDAPPREPORT._serialized_end=297
# @@protoc_insertion_point(module_scope)
