# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: e3sm_oai_l1_kpm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x65\x33sm_oai_l1_kpm.proto\x12\re3sm.l1kpm.v1\"P\n\x0bL1KPMShmRef\x12\x10\n\x08shm_name\x18\x01 \x01(\x0c\x12\x17\n\x0f\x66h_buffer_index\x18\x02 \x01(\r\x12\x16\n\x0e\x66h_write_index\x18\x03 \x01(\r\"\xb1\x01\n\x0fL1KPMIndication\x12\x32\n\x0eiq_samples_ref\x18\x01 \x01(\x0b\x32\x1a.e3sm.l1kpm.v1.L1KPMShmRef\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0b\n\x03sfn\x18\x03 \x01(\r\x12\x0c\n\x04slot\x18\x04 \x01(\r\x12\x0f\n\x07\x63\x65ll_id\x18\x05 \x01(\r\x12\x10\n\x08n_rx_ant\x18\x06 \x01(\r\x12\x19\n\x11valid_symbol_mask\x18\x07 \x01(\r\"J\n\x14L1KPMRanFunctionData\x12\x0c\n\x04name\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\x0c')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'e3sm_oai_l1_kpm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _L1KPMSHMREF._serialized_start=40
  _L1KPMSHMREF._serialized_end=120
  _L1KPMINDICATION._serialized_start=123
  _L1KPMINDICATION._serialized_end=300
  _L1KPMRANFUNCTIONDATA._serialized_start=302
  _L1KPMRANFUNCTIONDATA._serialized_end=376
# @@protoc_insertion_point(module_scope)
