name: Run tests

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.repository != 'wineslab/dApp-library'
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install hatch
        run: pip install hatch

      - name: Run tests
        run: hatch run pytest tests/ -v
